
[package]
authors = ["Enrico Risa <enrico.risa@prima.it>"]
edition = "2018"
name = "rust-ddd"
version = "0.1.0"
#efinitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
